### ISSUE TITLE
Towards v1.0

### ISSUE THREAD

**Issue by dkarrasch** [CoherentStructures/CoherentStructures.jl#13]
I think the package is in pretty good shape by now, so we could think about releasing a version 1.0. Before that, we should get the following things done:

- [x] finish #12
- [x] consciously handle the orientation issue in the closed orbit computation in `constrainedLCS` (should be easy)
- [x] include linear ODE integrators and showcase solving the advection-diffusion equation in Lagrangian coordinates (that's been done by Philipp Rohrmüller in #16)
- [ ] maybe tests of the FEM part?
- [ ] would be good, perhaps, to also turn on coverage testing (well, that should be done after we have some FEM tests, otherwise coverage will just look disastrous 😄).

Anything else to include?

**Comment by natschil** [comment]
The constrained LCS code still has some orientation issues I think that should be very easy to fix.

**Comment by natschil** [comment]
I think we can move the advection-diffusion equation showcase into a higher version, as it's kind of a new feature in a sense

**Comment by dkarrasch** [comment]
> I think we can move the advection-diffusion equation showcase into a higher version, as it's kind of a new feature in a sense

We have the relevant code now. We just need to add a page in the documentation, which is irrelevant to tagging versions.

**Comment by dkarrasch** [comment]
Tests and coverage remain general issues, but the release part of the issue has been resolved in a215762.
