### ISSUE TITLE
Some trouble with DISPLAY_PLOT

### ISSUE THREAD

**Issue by JiahanBro** [CoherentStructures/CoherentStructures.jl#14]
Hi guys, 
thanks for providing the toolbox! I have been trying to run the examples and I guess I have included all the necessary packages. Nevertheless I am always getting an error whenever the function DISPLAY_PLOT is called. In the case of the rot_double_gyre.jl example I have the following error:

ERROR: LoadError: UndefVarError: DISPLAY_PLOT not defined
Stacktrace:
 [1] top-level scope at none:0
 [2] include at ./boot.jl:317 [inlined]
 [3] include_relative(::Module, ::String) at ./loading.jl:1041
 [4] include(::Module, ::String) at ./sysimg.jl:29
 [5] include(::String) at ./client.jl:388
 [6] top-level scope at none:0

I already added PyPlot and Plots. Is there any Julia plot package which I am missing?

**Comment by dkarrasch** [comment]
Sure thing. You should run the linked source code

https://raw.githubusercontent.com/CoherentStructures/CoherentStructures.jl/gh-pages/dev/generated/rot_double_gyre.jl

(from the docs, click on the *.jl link here https://coherentstructures.github.io/CoherentStructures.jl/latest/generated/rot_double_gyre/),
not the files that are used to generate the documentation etc. We should be clear about this somewhere. I'd appreciate a suggestion where to explain this (from a user's perspective).

**Comment by dkarrasch** [comment]
I have added a comment in the README, referring interested users to the documentation for example code, so I'm closing this.

**Comment by JiahanBro** [comment]
Awesome! Thank you so much :)
