### ISSUE TITLE
DISPLAY_PLOT not defined

### ISSUE THREAD

**Issue by liaogh** [CoherentStructures/CoherentStructures.jl#31]
When I test the examples "bickley.jl", an error occurs as follows: "ERROR: LoadError: UndefVarError: DISPLAY_PLOT not defined", Is other packages needed?

**Comment by dkarrasch** [comment]
You should approach the `bickley.jl` file through the documentation, see the link in the green box at the top of this page

https://coherentstructures.github.io/CoherentStructures.jl/stable/generated/bickley/

That `jl` file should work as is.

**Comment by liaogh** [comment]
Thanks very much!
