### ISSUE TITLE
Ocean flow example in documentation shows only 3 vortices

### ISSUE THREAD

**Issue by natschil** [CoherentStructures/CoherentStructures.jl#6]
See https://coherentstructures.github.io/CoherentStructures.jl/latest/generated/ocean_flow/

**Comment by dkarrasch** [comment]
This must be some weird artifact. The build log shows that 5 vortices have been found, and when I run the online-code locally, it also finds 5 vortices. Let's see what happens after the next commit.

**Comment by dkarrasch** [comment]
Fixed by #5.
