### ISSUE TITLE
Error compiling in v1.7.0

### ISSUE THREAD

**Issue by oc-rodu** [CoherentStructures/CoherentStructures.jl#87]
Hello!

`julia> VERSION
v"1.7.0"`

`julia> Sys.iswindows()
true`

`julia> import Pkg; Pkg.precompile()`
Precompiling project...
  ✗ CoherentStructures
  0 dependencies successfully precompiled in 16 seconds (249 already precompiled)

ERROR: The following 1 direct dependency failed to precompile:

CoherentStructures [0c1513b4-3a13-56f1-9cd2-8312eaec88c4]

Failed to precompile CoherentStructures [0c1513b4-3a13-56f1-9cd2-8312eaec88c4] to C:\Users\Rodrigo\.julia\compiled\v1.7\CoherentStructures\jl_8DFF.tmp.
ERROR: LoadError: invalid subtyping in definition of LinearImplicitEuler
Stacktrace:
  [1] top-level scope
    @ C:\Users\Rodrigo\.julia\packages\CoherentStructures\CxxKh\src\odesolvers.jl:7
  [2] include(mod::Module, _path::String)
    @ Base .\Base.jl:418
  [3] include(x::String)
    @ CoherentStructures C:\Users\Rodrigo\.julia\packages\CoherentStructures\CxxKh\src\CoherentStructures.jl:1
  [4] top-level scope
    @ C:\Users\Rodrigo\.julia\packages\CoherentStructures\CxxKh\src\CoherentStructures.jl:104
  [5] include
    @ .\Base.jl:418 [inlined]
  [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base .\loading.jl:1318
  [7] top-level scope
    @ none:1
  [8] eval
    @ .\boot.jl:373 [inlined]
  [9] eval(x::Expr)
    @ Base.MainInclude .\client.jl:453
 [10] top-level scope
    @ none:1
in expression starting at C:\Users\Rodrigo\.julia\packages\CoherentStructures\CxxKh\src\odesolvers.jl:7
in expression starting at C:\Users\Rodrigo\.julia\packages\CoherentStructures\CxxKh\src\CoherentStructures.jl:1
Stacktrace:
 [1] pkgerror(msg::String)
   @ Pkg.Types C:\Users\Rodrigo\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Pkg\src\Types.jl:68
 [2] precompile(ctx::Pkg.Types.Context; internal_call::Bool, strict::Bool, warn_loaded::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ Pkg.API C:\Users\Rodrigo\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Pkg\src\API.jl:1362
 [3] precompile
   @ C:\Users\Rodrigo\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Pkg\src\API.jl:1013 [inlined]
 [4] #precompile#220
   @ C:\Users\Rodrigo\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Pkg\src\API.jl:1011 [inlined]
 [5] precompile()
   @ Pkg.API C:\Users\Rodrigo\AppData\Local\Programs\Julia-1.7.0\share\julia\stdlib\v1.7\Pkg\src\API.jl:1011
 [6] top-level scope

**Comment by oc-rodu** [comment]
I don't have problems with v1.5.4, but it seems to complain about julia's version:

(@v1.5) pkg> add https://github.com/CoherentStructures/CoherentStructures.jl.git
   Updating git-repo `https://github.com/CoherentStructures/CoherentStructures.jl.git`
   Updating registry at `C:\Users\Rodrigo\.julia\registries\General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
julia version requirement for package `CoherentStructures [0c1513b4]` not satisfied
No Changes to `C:\Users\Rodrigo\.julia\environments\v1.5\Project.toml`
No Changes to `C:\Users\Rodrigo\.julia\environments\v1.5\Manifest.toml`

**Comment by dkarrasch** [comment]
Thanks for the error report. This is fixed in #86, which I should finalize and release, hopefully tomorrow. Another option is to pin the package OrdinaryDiffEq to version 5.70. And yes, our package is not usable in Julia v1.5, it requires v1.6 at the least, but v1.7 is the current stable, hence recommended version.

**Comment by oc-rodu** [comment]
thanks, I can confirm the workaround solved the problem.
