### ISSUE TITLE
Cannot index SymmetricTensor

### ISSUE THREAD

**Issue by oc-rodu** [CoherentStructures/CoherentStructures.jl#88]
julia> VERSION
v"1.7.1"

And CoherentStructures is up to date.

In this example https://coherentstructures.github.io/CoherentStructures.jl/stable/generated/bickley/#Bickley-jet
a tensor D is defined for a non-identity diffusion tensor, which causes this error

```
C̅ = pmap(mCG_tensor, P; batch_size=ceil(Int, length(P)/nprocs()^2))
ERROR: On worker 2:
MethodError: objects of type SymmetricTensor{2, 2, Float64, 3} are not callable
Use square brackets [] for indexing an Array.
```
If I do not pass D by doing 

```
mCG_tensor = u -> av_weighted_CG_tensor(bickley, u, tspan, δ;
       tolerance=1e-6, solver=Tsit5())
```
instead of
```
mCG_tensor = u -> av_weighted_CG_tensor(bickley, u, tspan, δ;
        D=D, tolerance=1e-6, solver=Tsit5())
```
the problem disappears.

**Comment by oc-rodu** [comment]
Thanks this is helpful as I learn Julia+CoherentStructures.jl at the same time. I can confirm the option you suggest according to documentation `D=(_ -> D)` works. 

You may want to correct the example: (https://coherentstructures.github.io/CoherentStructures.jl/stable/generated/bickley/#Bickley-jet), the definition of `mCG_tensor  ` there is I posted earlier and will give an error:
```
mCG_tensor = u -> av_weighted_CG_tensor(bickley, u, tspan, δ;
        D=D, tolerance=1e-6, solver=Tsit5())
```

**Comment by dkarrasch** [comment]
Very strange: when I click on your link, then I see the `D=_ -> D`-version. Which version is displayed in the lower-left version box? The latest stable version is 0.4.7.

**Comment by dkarrasch** [comment]
Great, thanks for catching that. I'll go and fix it.

**Comment by oc-rodu** [comment]
thank you!

**Comment by dkarrasch** [comment]
Just in case you need to define custom diffusion tensors, please use round brackets instead of square ones! I fixed it in the docs, that was definitely suboptimal syntax.
