### ISSUE TITLE
OECS results in intersecting eddies 

### ISSUE THREAD

**Issue by oc-rodu** [CoherentStructures/CoherentStructures.jl#95]
I did the example for OECS shown [here](https://coherentstructures.github.io/CoherentStructures.jl/stable/generated/ocean_flow/) but with the following changes:  

`xmin, xmax, ymin, ymax = minimum(xs), maximum(xs), minimum(ys), maximum(ys)`

and  (note I am using the fifth time instead of the first as in the example):
`const V = scale(interpolate(SVector{2}.(us[:,:,5], vs[:,:,5]), BSpline(Quadratic(Free(OnGrid())))), xs, ys)`

I get two eddies that intersect each other between 25 and 30 South and around 6 West (figure below), making it impossible for these "eddy" boundaries to be transport barriers. What could be the problem?

Thanks.

![image](https://user-images.githubusercontent.com/27505750/177188384-7bc53fa5-aafd-4a96-baa4-b7e07d768650.png)

**Comment by dkarrasch** [comment]
As you can see, this computation is super sensitive: there are plenty of singularities at which the line fields change direction drastically. Another issue I see with the larger one is that the indices of the enclosed singularities don't seem to add up to 1. So one could use that as a postprocessing filter. If you need help with that, I can take a look. Basically, one could compute the "winding number" of a closed curve (such as the output of the elliptic LCS functions) w.r.t. all the singularities. Those that have a non-vanishing winding number are "inside" the closed curve. One could then add up their indices and check if it's 1.

Generally speaking, OECS are computed from instantaneous velocity data. For that reason, the only make sense instantaneously, whereas transport is in my opinion a finite-time process. I'm not sure one would interpret OECS as "transport barriers" anyway.

**Comment by oc-rodu** [comment]
Thanks very much. I would appreciate your help implementing the winding number constraint you mention. I would even suggest that this constraint should be part of CoherentStructures.jl for the following reason:

OECS are computed from an instantaneous field, however, the claim by Serra & Haller is that they hold for a small enough time interval about that instantaneous time, therefore I do not see any problem with interpreting OECS as Lagrangian transport barriers if the trajectories to verify such a claim belong to the time interval over which OECS are supposed to hold. What exactly is that time interval over which they are valid? That is an open question than needs further research, at least in the physical oceanography applications I am interested in. To be able to research the Haller & Serra claim, we need a numerical method to extract OECS as transport barriers which is the reason I would suggest the winding number constraint you mention should be implemented. 

I would offer to help but since I am learning Julia from scratch, as time permits, to use CoherentStructures.jl, it will probably take me too much time for this to be a good idea.

**Comment by dkarrasch** [comment]
No worries. I'll give it a shot.

**Comment by dkarrasch** [comment]
In the next PR, there will be a new convenience function `isinside(p, vortex)`. You can then check the vortices if they "make sense" in the sense whether the indices of the enclosed singularities sum up to 1 as follows:

```julia
check_vortex(poly::Vector{<:SVector{2}}, singularities::Vector{Singularity}) =
    isone(sum(s.index for s in singularities if isinside(s, poly)))
check_vortex(barrier::EllipticBarrier, singularities::Vector{Singularity}) =
    check_vortex(barrier.curve, singularities)
check_vortex(vortex::EllipticVortex, singularities::Vector{Singularity}) =
    check_vortex(last(vortex.barriers), singularities)
```

I won't add these functions as it appears to me unclear what different users may want to check about their vortices. But you could filter you vortices with the above functions as follows:

```julia
vortices, singularities = ... # as in the docs
filtered_vortices = [vortex for vortex in vortices if check_vortex(vortex, singularities)]
```

For me, that catches two vortices out of the 9.

As I think about it, one could potentially include such a check in the actual computation and output only those that satisify the index rule... I'll play with it some more.
