### ISSUE TITLE
No elliptic barrier found

### ISSUE THREAD

**Issue by lunahiron** [CoherentStructures/CoherentStructures.jl#98]
Hi everyone, 

I have used the CoherentStructure code in the past to find Lagrangian coherent contours from an altimetry-derived velocity field, and it worked fine. However, I updated all libraries last week; the code ran fine, but no elliptic barrier was identified for the same dataset. 

I then tried to run the ocean_flow.jl ([example](https://coherentstructures.github.io/CoherentStructures.jl/stable/generated/ocean_flow/)), and the problem persists: no elliptic barrier is identified. Please, see below the results for both my analysis and the ocean_flow.jl example. 

I am using Julia v1.8.5 and CoherentStructures v0.4.11.

Do you have insights on what could be happening?
Thank you!

<img width="842" alt="my_analysis" src="https://user-images.githubusercontent.com/37672819/225160098-59f1dd6f-096d-4c58-a838-36d2d65c8262.png">
<img width="1279" alt="ocean_flow_example" src="https://user-images.githubusercontent.com/37672819/225160100-e7928989-fabb-4be8-a909-87f8ee72a8ef.png">

**Comment by dkarrasch** [comment]
I am working on an internal update that accounts for changes in the ecosystem. Looks like breaking changes have been done without bumping the major version number, or, we use features of other packages that are considered too internal to warrant a major version bump.

**Comment by lunahiron** [comment]
Hi Daniel, I installed the `internal` branch and the code is running and working well. I was able to find the elliptic barriers. Thanks a lot for this quick fix!!

**Comment by dkarrasch** [comment]
I released a new version. You should now safely return to the default setting, as I'm going to remove the `internal` branch.
